In [1]:
import random 
import time
from copy import copy
import pprint
import numpy as np
import tensorflow as tf
from tensorflow.keras import models, layers

In [2]:
def create_board(nb_row, nb_col):
    if nb_row <= 0 or nb_col <= 0:
        raise ValueError()
    matrix = [['.'for j in range(nb_col)] for i in  range(nb_row)]
    return np.array(matrix)


def free_cols(plateau):
    index_nb = []
    i = 0
    while i < len(plateau[-1]):
        if plateau[-1][i] == '.':
            index_nb.append(i)
        i += 1
    return index_nb

def drop_piece(plateau, col, couleur):
    if couleur not in "RJ":
        raise ValueError("la couleur n'existe pas")
    if col not in free_cols(plateau):
        raise ValueError("La colonne est déjà remplie")
    if col < 0:
        raise ValueError("L’index de la colonne est < 0")
    i = 0
    while i < len(plateau):
        if plateau[i][col] == '.':
            plateau[i][col] = couleur
            break
        i += 1
    return plateau

def row_win(plateau, couleur):
    if couleur not in "RJ":
        raise ValueError("La couleur n’existe pas")
    i=0
    while i < len(plateau):
        j = 0
        while j < len(plateau[i]):
            a = 0; c = j
            while c < len(plateau[i]) and plateau[i][c] == couleur:
                a += 1
                c += 1
                if a == 4:
                    return True     
            j += 1
        i += 1
    return False

def col_win(plateau, couleur):
    if couleur not in "RJ":
        raise ValueError("La couleur n’existe pas")
    i = 0
    while i < len(plateau):
        j = 0
        while j < len(plateau[i]):
            a = 0
            h = i
            while h < len(plateau) and plateau[h][j] == couleur:
                a += 1
                h += 1
                if a == 4:
                    return True
            j += 1
        i += 1
    return False

def diag_win(plateau, couleur):
    if couleur not in "RJ":
        raise ValueError("La couleur n’existe pas")
    i = 0
    while i < len(plateau):
        j = 0
        while j < len(plateau[i]):
            a = 0; b = 0
            c = j; c1 = j
            r = i; r1 = i
            while r < len(plateau) and c < len(plateau[r]) and plateau[r][c] == couleur:
                r += 1
                c += 1
                a += 1
                if a == 4:
                    return True
            while r1 < len(plateau) and c1 >= 0 and plateau[r1][c1] == couleur:
                r1 += 1
                c1 -= 1
                b += 1
                if b == 4:
                     return True
            j += 1
        i += 1
    return False

In [3]:
def play_random(plateau, couleur):
    for i in plateau:
        if len(i) != 7 and len(plateau) != 6:
            raise ValueError("Erreur plateau")
    if len(free_cols(plateau)) == 0:
        raise ValueError("Plateau rempli")
    if couleur not in "RJ":
        raise ValueError("la couleur n'existe pas")
    col = random.choice(free_cols(plateau))
    return drop_piece(plateau, col, couleur)

In [4]:
matrix = create_board(6, 7)
g = 2
while row_win(matrix,"R") == False and row_win(matrix,"J") == False and diag_win(matrix, "J") == False \
        and diag_win(matrix, "R") == False and col_win(matrix, "R") == False and col_win(matrix, "J") == False:
    if g % 2 == 0:
        jeux = play_random(matrix, "R")
    else:
        jeux = play_random(matrix, "J")
    g += 1
    matrix = jeux 
    
for i in matrix:
    print(i)
if g % 2 == 0:
    print("Les jaunes ont gagnés")
else:
    print("Les rouges ont gagnés")

['R' 'J' 'J' 'J' 'R' 'J' 'J']
['J' 'R' 'R' 'J' 'R' 'R' 'R']
['.' '.' 'R' 'R' 'R' 'J' 'R']
['.' '.' 'J' 'R' 'J' 'R' 'J']
['.' '.' '.' '.' '.' 'R' 'J']
['.' '.' '.' '.' '.' 'J' '.']
Les rouges ont gagnés


In [5]:
class Player:

    def __init__(self, color):
        self.color = color
    
    def free_cols(self, plateau):
        index_nb = []
        i = 0
        while i < len(plateau[-1]):
            if plateau[-1][i] == 0:
                index_nb.append(i)
            i += 1
        return index_nb

    def drop_piece(self, plateau, col):
        if self.color not in "RJ":
            raise ValueError("la couleur n'existe pas")
        if col not in self.free_cols(plateau):
            raise ValueError("La colonne est déjà remplie")
        if col < 0:
            raise ValueError("L’index de la colonne est < 0")
        i = 0
        while i < len(plateau):
            if plateau[i][col] == 0:
                if self.color == 'R':
                    plateau[i][col] = 1
                    break
                else:
                    plateau[i][col] = -1
                    break
                    
            i += 1
        return plateau
    
    def play_random(self, plateau):
        for i in plateau:
            if len(i) != 7 and len(plateau) != 6:
                raise ValueError("Erreur plateau")
        if len(self.free_cols(plateau)) == 0:
            raise ValueError("Plateau rempli")
        if self.color not in "RJ":
            raise ValueError("la couleur n'existe pas")
        col = random.choice(self.free_cols(plateau))
        return self.drop_piece(plateau, col), col
    
    def my_color(self):
        return self.color
        
    

In [11]:
def row_win(plateau, couleur):
    i=0
    while i < len(plateau):
        j = 0
        while j < len(plateau[i]):
            a = 0; c = j
            while c < len(plateau[i]) and plateau[i][c] == couleur:
                a += 1
                c += 1
                if a == 4:
                    return True     
            j += 1
        i += 1
    return False

def col_win(plateau, couleur):
    i = 0
    while i < len(plateau):
        j = 0
        while j < len(plateau[i]):
            a = 0
            h = i
            while h < len(plateau) and plateau[h][j] == couleur:
                a += 1
                h += 1
                if a == 4:
                    return True
            j += 1
        i += 1
    return False

def diag_win(plateau, couleur):
    i = 0
    while i < len(plateau):
        j = 0
        while j < len(plateau[i]):
            a = 0; b = 0
            c = j; c1 = j
            r = i; r1 = i
            while r < len(plateau) and c < len(plateau[r]) and plateau[r][c] == couleur:
                r += 1
                c += 1
                a += 1
                if a == 4:
                    return True
            while r1 < len(plateau) and c1 >= 0 and plateau[r1][c1] == couleur:
                r1 += 1
                c1 -= 1
                b += 1
                if b == 4:
                     return True
            j += 1
        i += 1
    return False


def verification_plateau(matrix):
    if row_win(matrix,1) == False and row_win(matrix,-1) == False and diag_win(matrix, -1) == False \
        and diag_win(matrix, 1) == False and col_win(matrix, 1) == False and col_win(matrix, -1) == False:
        
        return False
    else : 
        return True 
    
    
def create_board(nb_row, nb_col):
    if nb_row <= 0 or nb_col <= 0:
        raise ValueError()
    matrix = [[0 for j in range(nb_col)] for i in  range(nb_row)]
    return np.array(matrix)
    
    

In [6]:
def reveal_plateau(test):
    matrixx = [['.'for j in range(test.shape[1])] for i in  range(test.shape[0])]
    for i in range(test.shape[0]):
        for j in range(test.shape[1]):
            if test[i][j] == 1:
                matrixx[i][j] = "R"
            elif test[i][j] == -1:
                matrixx[i][j] = "J"
                
    return matrixx

In [210]:
matrix = create_board(6, 7)
matrix

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [106]:
def model():
    entree=layers.Input(shape=(6,7,1), dtype='float32')
#     result=layers.Conv2D(  nbr_cc, 3, activation='relu', padding='same', strides=2)(entree)
    result=layers.Conv2D(64,(3,3), activation = 'relu')(entree)
    result=layers.Flatten()(result)
    result=layers.Dense(64, activation='relu')(result)
    result=layers.Dense(64, activation='relu')(result)
    sortie=layers.Dense(tf.constant(7))(result)
    
    model=models.Model(inputs=entree, outputs=sortie)
    return model
    
    
def my_loss(target_q, predicted_q):
    loss=tf.reduce_mean(tf.math.square(target_q-predicted_q))
    return loss

In [107]:
gamma=tf.constant(0.98)
nbr_action = 7

@tf.function
def train_step(reward, action, observation, next_observation, done):
    next_Q_values=model(next_observation)
    best_next_actions=tf.math.argmax(next_Q_values, axis=1)
    next_mask=tf.one_hot(best_next_actions, nbr_action)
#     print(next_Q_values, next_Q_values.shape)
#     print(next_mask, next_mask.shape)
    next_best_Q_values=tf.reduce_sum(next_Q_values*next_mask, axis=1)
#     print('Next best Q : ', next_best_Q_values)
    target_Q_values=reward+(1-done)*gamma*next_best_Q_values
    target_Q_values=tf.reshape(target_Q_values, (-1, 1))
    mask=tf.one_hot(action, nbr_action)
    with tf.GradientTape() as tape:
        all_Q_values=model(observation)
        Q_values=tf.reduce_sum(all_Q_values*mask, axis=1, keepdims=True)
        loss=my_loss(target_Q_values, Q_values)
    gradients=tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    train_loss(loss)

In [108]:
player_r = Player("R")
player_j = Player("J")

gamma=tf.constant(0.98)
epoch= 2000
best_score=0
tab_score = []

epsilon=1.
epsilon_min=0.10
start_epsilon=1
end_epsilon=epoch//2
epsilon_decay_value=epsilon/(end_epsilon-start_epsilon)



# matrix = create_board(6, 7)
# done = verification_plateau(matrix)
def train():
    global epsilon, best_score, tab_score
    for e in range(epoch):
#         g = 2

        hits = []
        plateaux = []
        plateaux_next = []
        rewards = []
        dones = []
        score = 0

        for _ in range(50):

            jeux = create_board(6, 7)
            done = verification_plateau(jeux)
            draw = False 
            error = False
            g = 2
#             print(done)


            while not done:
                reward = 0 
#                 print(reward)

                if g % 2 == 0:
                    plateaux.append(np.copy(jeux))

                    if random.random() > epsilon:
                        
                        valeurs_q=model(np.expand_dims(jeux, axis=0))
#                         print("observation brut : ", jeux) 
#                         print("observation shape : ", jeux.shape)
#                         print("the expand function : ", np.expand_dims(jeux, axis=0))
#                         print("the expand shape : ", np.expand_dims(jeux, axis=0).shape)
#                         print('Qvalue : ', valeurs_q)
                        hit = int(tf.argmax(valeurs_q[0], axis=-1))
                        if hit not in player_r.free_cols(jeux):
                            error = True 
                            done = True
                        else:
                            jeux = player_r.drop_piece(jeux, hit)
    

                    else :
                        jeux, hit = player_r.play_random(jeux)

                    hits.append(hit)
                    plateaux_next.append(np.copy(jeux))
#                     print(reward)
                    rewards.append(reward)
                    dones.append(done)

                else:
                    jeux, hit = player_j.play_random(jeux)
                g += 1
#                 matrix = jeux.copy() 
            #     plateaux.append(matrix)

                done = verification_plateau(jeux)

                if len(player_j.free_cols(jeux)) == 0 or len(player_r.free_cols(jeux)) == 0:
                    done = True 
                    draw = True 
            #     pprint.pprint(matrix)

    #         pprint.pprint(reveal_plateau(jeux))
            # print(matrix)

            if g % 2 == 0 or draw:
#                 print(rewards)
                if error == True:
                    reward = -20
                    rewards[-1] = reward
                else:
                    reward = -10
                    rewards[-1] = reward
        #         print("Les jaunes ont gagnés")
            else:
                reward = 10
#                 print(rewards)
                rewards[-1] = reward
                score += 1
        #         print("Les rouges ont gagnés")
            dones[-1] = done
#         print("num d'époque : ", e)
#         print(str(score*100/50), ' %')
#         print("plateaux : ", len(plateaux))
#         print("Hits : ", len(hits))


        tab_rewards=np.array(rewards, dtype=np.float32)
        tab_actions=np.array(hits, dtype=np.int32)
        tab_observations=np.expand_dims(np.array(plateaux, dtype=np.float32), axis=3)
        tab_next_observations=np.expand_dims(np.array(plateaux_next, dtype=np.float32), axis=3)
        tab_done=np.array(dones, dtype=np.float32)
#         print('Tout ce qui rentre dans train_step : ', tab_next_observations, tab_next_observations.shape)
        train_step(tab_rewards, tab_actions, tab_observations, tab_next_observations, tab_done)
        train_loss.reset_states()    

        print('Epoque : ', e, ' Score : ', score, ' / 50')
        tab_score.append(score)
        epsilon-=epsilon_decay_value
        epsilon=max(epsilon, epsilon_min)
        if np.mean(tab_score[-20:])>best_score:
            print("Sauvegarde du modele")
            model.save("my_model")
            best_score=np.mean(tab_score[-20:])
        if best_score==50:
            print('Finito, époque : ', e)
            return


In [109]:
model=model()
optimizer=tf.keras.optimizers.Adam(learning_rate=1E-4)
train_loss=tf.keras.metrics.Mean()
tab_s=[]

tab_score=[]
train()

Epoque :  0  Score :  28  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  1  Score :  28  / 50
Epoque :  2  Score :  28  / 50
Epoque :  3  Score :  28  / 50
Epoque :  4  Score :  29  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  5  Score :  26  / 50
Epoque :  6  Score :  22  / 50
Epoque :  7  Score :  34  / 50
Epoque :  8  Score :  30  / 50
Epoque :  9  Score :  29  / 50
Epoque :  10  Score :  24  / 50
Epoque :  11  Score :  28  / 50
Epoque :  12  Score :  28  / 50
Epoque :  13  Score :  24  / 50
Epoque :  14  Score :  23  / 50
Epoque :  15  Score :  22  / 50
Epoque :  16  Score :  25  / 50
Epoque :  17  Score :  25  / 50
Epoque :  18  Score :  29  / 50
Epoque :  19  Score :  25  / 50
Epoque :  20  Score :  30  / 50
Epoque :  21  Score :  25  / 50
Epoque :  22  Score :  27  / 50
Epoque :  23  Score :  35  / 50
Epoque :  24  Score :  29  / 50
Epoque :  25  Score :  33  / 50
Epoque :  26  Score :  30  / 50
Ep

INFO:tensorflow:Assets written to: my_model\assets
Epoque :  123  Score :  31  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  124  Score :  34  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  125  Score :  31  / 50
Epoque :  126  Score :  32  / 50
Epoque :  127  Score :  33  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  128  Score :  23  / 50
Epoque :  129  Score :  28  / 50
Epoque :  130  Score :  32  / 50
Epoque :  131  Score :  32  / 50
Epoque :  132  Score :  33  / 50
Epoque :  133  Score :  30  / 50
Epoque :  134  Score :  28  / 50
Epoque :  135  Score :  25  / 50
Epoque :  136  Score :  27  / 50
Epoque :  137  Score :  37  / 50
Epoque :  138  Score :  29  / 50
Epoque :  139  Score :  37  / 50
Epoque :  140  Score :  29  / 50
Epoque :  141  Score :  37  / 50
Epoque :  142  Score :  33  / 50
Epoque :  143  Score :  29  / 50
Epoque :  144  Score :  26  / 50
Epoque 

INFO:tensorflow:Assets written to: my_model\assets
Epoque :  269  Score :  37  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  270  Score :  33  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  271  Score :  31  / 50
Epoque :  272  Score :  32  / 50
Epoque :  273  Score :  32  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  274  Score :  36  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  275  Score :  24  / 50
Epoque :  276  Score :  33  / 50
Epoque :  277  Score :  35  / 50
Epoque :  278  Score :  34  / 50
Epoque :  279  Score :  26  / 50
Epoque :  280  Score :  35  / 50
Epoque :  281  Score :  35  / 50
Epoque :  282  Score :  28  / 50
Epoque :  283  Score :  33  / 50
Epoque :  284  Score :  29  / 50
Epoque :  285  Score :  25  / 50
Epoque :  286  Score :  34  / 50
Epoque :  287  Score :  34  / 50
Epoque :  288  Score :  34  / 50
E

INFO:tensorflow:Assets written to: my_model\assets
Epoque :  392  Score :  43  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  393  Score :  35  / 50
Epoque :  394  Score :  38  / 50
Epoque :  395  Score :  33  / 50
Epoque :  396  Score :  40  / 50
Epoque :  397  Score :  41  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  398  Score :  29  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  399  Score :  33  / 50
Epoque :  400  Score :  36  / 50
Epoque :  401  Score :  41  / 50
Epoque :  402  Score :  36  / 50
Epoque :  403  Score :  26  / 50
Epoque :  404  Score :  37  / 50
Epoque :  405  Score :  30  / 50
Epoque :  406  Score :  31  / 50
Epoque :  407  Score :  42  / 50
Epoque :  408  Score :  34  / 50
Epoque :  409  Score :  31  / 50
Epoque :  410  Score :  40  / 50
Epoque :  411  Score :  36  / 50
Epoque :  412  Score :  35  / 50
Epoque :  413  Score :  40  / 50
Epoque 

Epoque :  544  Score :  39  / 50
Epoque :  545  Score :  41  / 50
Epoque :  546  Score :  37  / 50
Epoque :  547  Score :  41  / 50
Epoque :  548  Score :  42  / 50
Epoque :  549  Score :  36  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  550  Score :  37  / 50
Epoque :  551  Score :  41  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  552  Score :  39  / 50
Epoque :  553  Score :  37  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  554  Score :  37  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  555  Score :  35  / 50
Epoque :  556  Score :  41  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  557  Score :  41  / 50
Epoque :  558  Score :  33  / 50
Epoque :  559  Score :  32  / 50
Epoque :  560  Score :  37  / 50
Epoque :  561  Score :  40  / 50
Epoque :  562  Score :  38  / 50
Epoque :  563

Epoque :  668  Score :  44  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  669  Score :  39  / 50
Epoque :  670  Score :  41  / 50
Epoque :  671  Score :  40  / 50
Epoque :  672  Score :  42  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  673  Score :  43  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  674  Score :  44  / 50
Epoque :  675  Score :  44  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  676  Score :  38  / 50
Epoque :  677  Score :  45  / 50
Epoque :  678  Score :  42  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  679  Score :  44  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  680  Score :  44  / 50
Sauvegarde du modele
INFO:tensorflow:Assets written to: my_model\assets
Epoque :  681  Score :  42  / 50
Sauvegarde du modele
INFO:tensorfl

Epoque :  858  Score :  41  / 50
Epoque :  859  Score :  42  / 50
Epoque :  860  Score :  37  / 50
Epoque :  861  Score :  37  / 50
Epoque :  862  Score :  43  / 50
Epoque :  863  Score :  45  / 50
Epoque :  864  Score :  44  / 50
Epoque :  865  Score :  40  / 50
Epoque :  866  Score :  41  / 50
Epoque :  867  Score :  45  / 50
Epoque :  868  Score :  45  / 50
Epoque :  869  Score :  44  / 50
Epoque :  870  Score :  43  / 50
Epoque :  871  Score :  45  / 50
Epoque :  872  Score :  38  / 50
Epoque :  873  Score :  36  / 50
Epoque :  874  Score :  38  / 50
Epoque :  875  Score :  39  / 50
Epoque :  876  Score :  41  / 50
Epoque :  877  Score :  42  / 50
Epoque :  878  Score :  40  / 50
Epoque :  879  Score :  43  / 50
Epoque :  880  Score :  46  / 50
Epoque :  881  Score :  48  / 50
Epoque :  882  Score :  39  / 50
Epoque :  883  Score :  39  / 50
Epoque :  884  Score :  42  / 50
Epoque :  885  Score :  46  / 50
Epoque :  886  Score :  43  / 50
Epoque :  887  Score :  44  / 50
Epoque :  

Epoque :  1047  Score :  41  / 50
Epoque :  1048  Score :  44  / 50
Epoque :  1049  Score :  45  / 50
Epoque :  1050  Score :  44  / 50
Epoque :  1051  Score :  46  / 50
Epoque :  1052  Score :  40  / 50
Epoque :  1053  Score :  47  / 50
Epoque :  1054  Score :  43  / 50
Epoque :  1055  Score :  44  / 50
Epoque :  1056  Score :  47  / 50
Epoque :  1057  Score :  42  / 50
Epoque :  1058  Score :  44  / 50
Epoque :  1059  Score :  42  / 50
Epoque :  1060  Score :  42  / 50
Epoque :  1061  Score :  39  / 50
Epoque :  1062  Score :  40  / 50
Epoque :  1063  Score :  43  / 50
Epoque :  1064  Score :  44  / 50
Epoque :  1065  Score :  45  / 50
Epoque :  1066  Score :  45  / 50
Epoque :  1067  Score :  44  / 50
Epoque :  1068  Score :  43  / 50
Epoque :  1069  Score :  43  / 50
Epoque :  1070  Score :  45  / 50
Epoque :  1071  Score :  47  / 50
Epoque :  1072  Score :  47  / 50
Epoque :  1073  Score :  46  / 50
Epoque :  1074  Score :  45  / 50
Epoque :  1075  Score :  44  / 50
Epoque :  1076

Epoque :  1267  Score :  43  / 50
Epoque :  1268  Score :  45  / 50
Epoque :  1269  Score :  44  / 50
Epoque :  1270  Score :  44  / 50
Epoque :  1271  Score :  41  / 50
Epoque :  1272  Score :  43  / 50
Epoque :  1273  Score :  41  / 50
Epoque :  1274  Score :  47  / 50
Epoque :  1275  Score :  44  / 50
Epoque :  1276  Score :  50  / 50
Epoque :  1277  Score :  45  / 50
Epoque :  1278  Score :  46  / 50
Epoque :  1279  Score :  41  / 50
Epoque :  1280  Score :  44  / 50
Epoque :  1281  Score :  38  / 50
Epoque :  1282  Score :  42  / 50
Epoque :  1283  Score :  44  / 50
Epoque :  1284  Score :  41  / 50
Epoque :  1285  Score :  45  / 50
Epoque :  1286  Score :  48  / 50
Epoque :  1287  Score :  45  / 50
Epoque :  1288  Score :  45  / 50
Epoque :  1289  Score :  42  / 50
Epoque :  1290  Score :  46  / 50
Epoque :  1291  Score :  44  / 50
Epoque :  1292  Score :  45  / 50
Epoque :  1293  Score :  46  / 50
Epoque :  1294  Score :  47  / 50
Epoque :  1295  Score :  43  / 50
Epoque :  1296

Epoque :  1508  Score :  42  / 50
Epoque :  1509  Score :  42  / 50
Epoque :  1510  Score :  40  / 50
Epoque :  1511  Score :  44  / 50
Epoque :  1512  Score :  48  / 50
Epoque :  1513  Score :  47  / 50
Epoque :  1514  Score :  46  / 50
Epoque :  1515  Score :  39  / 50
Epoque :  1516  Score :  40  / 50
Epoque :  1517  Score :  45  / 50
Epoque :  1518  Score :  39  / 50
Epoque :  1519  Score :  39  / 50
Epoque :  1520  Score :  42  / 50
Epoque :  1521  Score :  44  / 50
Epoque :  1522  Score :  44  / 50
Epoque :  1523  Score :  41  / 50
Epoque :  1524  Score :  42  / 50
Epoque :  1525  Score :  44  / 50
Epoque :  1526  Score :  41  / 50
Epoque :  1527  Score :  44  / 50
Epoque :  1528  Score :  43  / 50
Epoque :  1529  Score :  41  / 50
Epoque :  1530  Score :  42  / 50
Epoque :  1531  Score :  43  / 50
Epoque :  1532  Score :  42  / 50
Epoque :  1533  Score :  44  / 50
Epoque :  1534  Score :  39  / 50
Epoque :  1535  Score :  41  / 50
Epoque :  1536  Score :  41  / 50
Epoque :  1537

Epoque :  1749  Score :  40  / 50
Epoque :  1750  Score :  41  / 50
Epoque :  1751  Score :  42  / 50
Epoque :  1752  Score :  34  / 50
Epoque :  1753  Score :  41  / 50
Epoque :  1754  Score :  34  / 50
Epoque :  1755  Score :  36  / 50
Epoque :  1756  Score :  33  / 50
Epoque :  1757  Score :  38  / 50
Epoque :  1758  Score :  36  / 50
Epoque :  1759  Score :  30  / 50
Epoque :  1760  Score :  34  / 50
Epoque :  1761  Score :  38  / 50
Epoque :  1762  Score :  40  / 50
Epoque :  1763  Score :  30  / 50
Epoque :  1764  Score :  33  / 50
Epoque :  1765  Score :  40  / 50
Epoque :  1766  Score :  39  / 50
Epoque :  1767  Score :  41  / 50
Epoque :  1768  Score :  40  / 50
Epoque :  1769  Score :  41  / 50
Epoque :  1770  Score :  39  / 50
Epoque :  1771  Score :  34  / 50
Epoque :  1772  Score :  40  / 50
Epoque :  1773  Score :  33  / 50
Epoque :  1774  Score :  39  / 50
Epoque :  1775  Score :  33  / 50
Epoque :  1776  Score :  40  / 50
Epoque :  1777  Score :  40  / 50
Epoque :  1778

Epoque :  1990  Score :  37  / 50
Epoque :  1991  Score :  35  / 50
Epoque :  1992  Score :  39  / 50
Epoque :  1993  Score :  42  / 50
Epoque :  1994  Score :  42  / 50
Epoque :  1995  Score :  39  / 50
Epoque :  1996  Score :  36  / 50
Epoque :  1997  Score :  41  / 50
Epoque :  1998  Score :  41  / 50
Epoque :  1999  Score :  40  / 50


In [17]:
player_r = Player("R")
player_j = Player("J")

gamma=tf.constant(0.98)
epoch= 30
best_score=0
tab_score = []

epsilon=1.
epsilon_min=0.10
start_epsilon=1
end_epsilon=epoch//2
epsilon_decay_value=epsilon/(end_epsilon-start_epsilon)



# matrix = create_board(6, 7)
# done = verification_plateau(matrix)
# def train():
#     global epsilon, best_score, tab_score
for e in range(epoch):
    g = 2

    hits = []
    plateaux = []
    plateaux_next = []
    rewards = []
    dones = []
    score = 0

    for _ in range(50):

        matrix = create_board(6, 7)
        done = verification_plateau(matrix)
        draw = False 

        g += 1

        while not done:
            reward = 0 

            if g % 2 == 0:
                plateaux.append(np.copy(matrix))

                if random.random() > epsilon :
                    valeurs_q=model(np.expand_dims(observations, axis=0))
                    action=int(tf.argmax(valeurs_q[0], axis=-1))
#                         player_r.drop_piece(matrix, 3)


                else :
                    jeux, hit = player_r.play_random(matrix)

                hits.append(hit)
                plateaux_next.append(np.copy(jeux))
                rewards.append(reward)
                dones.append(done)

            else:
                jeux, hit = player_j.play_random(matrix)
            g += 1
            matrix = jeux.copy() 
        #     plateaux.append(matrix)

            done = verification_plateau(matrix)

            if len(player_j.free_cols(matrix)) == 0 or len(player_r.free_cols(matrix)) == 0:
                done = True 
                draw = True 
        #     pprint.pprint(matrix)

#         pprint.pprint(reveal_plateau(jeux))
        # print(matrix)

        if g % 2 == 0 or draw:
            reward = -10
            rewards[-1] = reward
            score += 1
    #         print("Les jaunes ont gagnés")
        else:
            reward = 10
            rewards[-1] = reward
    #         print("Les rouges ont gagnés")
        dones[-1] = done
    print("num d'époque : ", e)
    print(str(score*100/50), ' %')
    print("plateaux : ", len(plateaux))
    print("Hits : ", len(hits))


    tab_rewards=np.array(rewards, dtype=np.float32)
    tab_actions=np.array(hits, dtype=np.int8)
    tab_observations=np.array(plateaux, dtype=np.int8)
    tab_next_observations=np.array(plateaux_next, dtype=np.int8)
    tab_done=np.array(dones, dtype=np.int8)
#         train_step(tab_rewards, tab_actions, tab_observations, tab_next_observations, tab_done)
#         train_loss.reset_states()    

#         tab_score.append(score)
#         epsilon-=epsilon_decay_value
#         epsilon=max(epsilon, epsilon_min)
#         if np.mean(tab_score[-20:])>best_score:
#             print("Sauvegarde du modele")
#             model.save("my_model")
#             best_score=np.mean(tab_score[-20:])
#         if best_score==50:
#             print('Finito, époque : ', e)
#             return


num d'époque :  0
40.0  %
plateaux :  552
Hits :  552
num d'époque :  1
26.0  %
plateaux :  555
Hits :  555
num d'époque :  2
48.0  %
plateaux :  560
Hits :  560
num d'époque :  3
58.0  %
plateaux :  563
Hits :  563
num d'époque :  4
54.0  %
plateaux :  501
Hits :  501
num d'époque :  5
70.0  %
plateaux :  514
Hits :  514
num d'époque :  6
56.0  %
plateaux :  519
Hits :  519
num d'époque :  7
46.0  %
plateaux :  511
Hits :  511
num d'époque :  8
48.0  %
plateaux :  546
Hits :  546
num d'époque :  9
52.0  %
plateaux :  533
Hits :  533
num d'époque :  10
58.0  %
plateaux :  528
Hits :  528
num d'époque :  11
52.0  %
plateaux :  542
Hits :  542
num d'époque :  12
46.0  %
plateaux :  541
Hits :  541
num d'époque :  13
50.0  %
plateaux :  543
Hits :  543
num d'époque :  14
34.0  %
plateaux :  530
Hits :  530
num d'époque :  15
54.0  %
plateaux :  540
Hits :  540
num d'époque :  16
50.0  %
plateaux :  548
Hits :  548
num d'époque :  17
62.0  %
plateaux :  494
Hits :  494
num d'époque :  18
5

In [365]:
observations = tab_observations[0]

np.expand_dims(observations, axis=0).shape

(1, 6, 7)

In [225]:
print(matrix)
reveal_plateau(matrix)

[[ 1 -1  1 -1  1 -1  1]
 [-1 -1  1 -1 -1 -1  1]
 [ 0  1 -1  1  1  1 -1]
 [ 0  1  1  1  1 -1  1]
 [ 0 -1  0 -1 -1 -1  0]
 [ 0  0  0  0  0  1  0]]


[['R', 'J', 'R', 'J', 'R', 'J', 'R'],
 ['J', 'J', 'R', 'J', 'J', 'J', 'R'],
 ['.', 'R', 'J', 'R', 'R', 'R', 'J'],
 ['.', 'R', 'R', 'R', 'R', 'J', 'R'],
 ['.', 'J', '.', 'J', 'J', 'J', '.'],
 ['.', '.', '.', '.', '.', 'R', '.']]

In [215]:
hits, rewards, np.array(dones).astype('int')

([6, 2, 6, 0, 3, 2, 5, 4, 1, 1, 3, 5, 6, 4, 4, 2],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10],
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]))

In [216]:
plateaux[3], plateaux_next[3]

(array([[ 0,  0,  1, -1,  0, -1,  1],
        [ 0,  0,  0,  0,  0,  0,  1],
        [ 0,  0,  0,  0,  0,  0, -1],
        [ 0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0]]),
 array([[ 1,  0,  1, -1,  0, -1,  1],
        [ 0,  0,  0,  0,  0,  0,  1],
        [ 0,  0,  0,  0,  0,  0, -1],
        [ 0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0]]))

In [217]:
test = np.copy(plateaux[3])

In [218]:
test

array([[ 0,  0,  1, -1,  0, -1,  1],
       [ 0,  0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [223]:
pprint.pprint(reveal_plateau(test))

[['.', '.', 'R', 'J', '.', 'J', 'R'],
 ['.', '.', '.', '.', '.', '.', 'R'],
 ['.', '.', '.', '.', '.', '.', 'J'],
 ['.', '.', '.', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.', '.', '.']]


In [153]:
test.astype('float')

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [54]:
b

array([[1, 2, 3],
       [7, 2, 3]])

In [55]:
a

array([[1, 2, 3],
       [1, 2, 3]])

In [235]:
random.random()

0.05445717884270407

In [55]:
import gym
import tensorflow as tf
from tensorflow.keras import models, layers
import numpy as np

env = gym.make("CartPole-v0")
env._max_episode_steps=500
nbr_action=2

gamma=tf.constant(0.98)
epoch=10
best_score=0

epsilon=1.
epsilon_min=0.10
start_epsilon=1
end_epsilon=epoch//2
epsilon_decay_value=epsilon/(end_epsilon-start_epsilon)

def model():
  entree=layers.Input(shape=(4), dtype='float32')
  result=layers.Dense(30, activation='relu')(entree)
  result=layers.Dense(30, activation='relu')(result)
  sortie=layers.Dense(nbr_action)(result)
    
  model=models.Model(inputs=entree, outputs=sortie)
  return model

def my_loss(target_q, predicted_q):
  loss=tf.reduce_mean(tf.math.square(target_q-predicted_q))
  return loss

@tf.function
def train_step(reward, action, observation, next_observation, done):
    next_Q_values=model(next_observation)
    best_next_actions=tf.math.argmax(next_Q_values, axis=1)
    next_mask=tf.one_hot(best_next_actions, nbr_action)
    print('pb1',next_Q_values, next_Q_values.shape)
    print('pb2', next_mask, next_mask.shape)
    next_best_Q_values=tf.reduce_sum(next_Q_values*next_mask, axis=1)
    target_Q_values=reward+(1-done)*gamma*next_best_Q_values
    target_Q_values=tf.reshape(target_Q_values, (-1, 1))
    mask=tf.one_hot(action, nbr_action)
    with tf.GradientTape() as tape:
        all_Q_values=model(observation)
        Q_values=tf.reduce_sum(all_Q_values*mask, axis=1, keepdims=True)
        loss=my_loss(target_Q_values, Q_values)
    gradients=tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    train_loss(loss)

def train(debug=False):
    global epsilon, best_score, tab_score
    for e in range(epoch):
        print("EPOCH:", e, "epsilon", epsilon)
        score=0
        tab_observations=[]
        tab_rewards=[]
        tab_actions=[]
        tab_next_observations=[]
        tab_done=[]
    
        observations=env.reset()
        while True:
            

            tab_observations.append(observations)    
            if np.random.random()>epsilon:
                valeurs_q=model(np.expand_dims(observations, axis=0))
                print("observation brut : ", observations) 
                print("observation shape : ", observations.shape)
                print(observations.shape)
                print("the expand function : ", np.expand_dims(observations, axis=0))
                print("the expand shape : ", np.expand_dims(observations, axis=0).shape)
                action=int(tf.argmax(valeurs_q[0], axis=-1))
            else:
                action=np.random.randint(0, nbr_action)
            observations, reward, done, info=env.step(action)
            tab_actions.append(action)
            tab_next_observations.append(observations)
            tab_done.append(done)
            if done:
                tab_rewards.append(-10.)
                print("FIN, score:", score)
                tab_score.append(score)
                score=0
                break
            score+=1
            tab_rewards.append(reward)

        tab_rewards=np.array(tab_rewards, dtype=np.float32)
        tab_actions=np.array(tab_actions, dtype=np.int32)
        tab_observations=np.array(tab_observations, dtype=np.float32)
        tab_next_observations=np.array(tab_next_observations, dtype=np.float32)
        tab_done=np.array(tab_done, dtype=np.float32)
        print('Tout ce qui rentre dans train_step : ', tab_next_observations, tab_next_observations.shape)
        train_step(tab_rewards, tab_actions, tab_observations, tab_next_observations, tab_done)
        train_loss.reset_states()

        epsilon-=epsilon_decay_value
        epsilon=max(epsilon, epsilon_min)
        if np.mean(tab_score[-20:])>best_score:
            print("Sauvegarde du modele")
            model.save("my_model")
            best_score=np.mean(tab_score[-20:])
            if best_score==env._max_episode_steps-1:
                return
      
model=model()
optimizer=tf.keras.optimizers.Adam(learning_rate=1E-4)
train_loss=tf.keras.metrics.Mean()
tab_s=[]

tab_score=[]
train()

np.save("tab_score", tab_score)

C:\Users\melik\anaconda3\envs\my-rdkit-env\lib\site-packages\gym\envs\registration.py:564: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.warn(
C:\Users\melik\anaconda3\envs\my-rdkit-env\lib\site-packages\gym\utils\passive_env_checker.py:97: UserWarning: WARN: We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html
  logger.warn(


EPOCH: 0 epsilon 1.0
FIN, score: 20
Tout ce qui rentre dans train_step :  [[ 0.04713485  0.1608257  -0.01175645 -0.2544402 ]
 [ 0.05035137 -0.03412644 -0.01684525  0.03451149]
 [ 0.04966884  0.16123298 -0.01615502 -0.2634383 ]
 [ 0.0528935   0.35658175 -0.02142379 -0.5611726 ]
 [ 0.06002513  0.16176692 -0.03264724 -0.27531552]
 [ 0.06326047 -0.0328744  -0.03815355  0.00689427]
 [ 0.06260298 -0.22742899 -0.03801567  0.28729936]
 [ 0.0580544  -0.42198876 -0.03226968  0.56775427]
 [ 0.04961463 -0.61664355 -0.0209146   0.8500988 ]
 [ 0.03728176 -0.81147414 -0.00391262  1.1361324 ]
 [ 0.02105227 -0.61630124  0.01881003  0.8422249 ]
 [ 0.00872625 -0.81167483  0.03565453  1.1407633 ]
 [-0.00750725 -0.61703664  0.05846979  0.8594717 ]
 [-0.01984798 -0.8129042   0.07565922  1.1699512 ]
 [-0.03610606 -0.6188433   0.09905825  0.9019153 ]
 [-0.04848293 -0.81515765  0.11709656  1.2240188 ]
 [-0.06478608 -0.62172216  0.14157693  0.97020024]
 [-0.07722053 -0.8184313   0.16098094  1.3037965 ]
 [-0.093

observation brut :  [-0.01672419 -0.7961032   0.02890114  1.216554  ]
observation shape :  (4,)
(4,)
the expand function :  [[-0.01672419 -0.7961032   0.02890114  1.216554  ]]
the expand shape :  (1, 4)
observation brut :  [-0.03264625 -0.9915857   0.05323222  1.5181512 ]
observation shape :  (4,)
(4,)
the expand function :  [[-0.03264625 -0.9915857   0.05323222  1.5181512 ]]
the expand shape :  (1, 4)
observation brut :  [-0.05247797 -1.1873095   0.08359524  1.8269638 ]
observation shape :  (4,)
(4,)
the expand function :  [[-0.05247797 -1.1873095   0.08359524  1.8269638 ]]
the expand shape :  (1, 4)
observation brut :  [-0.07622416 -1.3832529   0.12013452  2.1444008 ]
observation shape :  (4,)
(4,)
the expand function :  [[-0.07622416 -1.3832529   0.12013452  2.1444008 ]]
the expand shape :  (1, 4)
observation brut :  [-0.10388921 -1.5793375   0.16302253  2.4716425 ]
observation shape :  (4,)
(4,)
the expand function :  [[-0.10388921 -1.5793375   0.16302253  2.4716425 ]]
the expand s

EPOCH: 8 epsilon 0.1
observation brut :  [ 0.0097797  -0.21745624  0.00357116  0.33863607]
observation shape :  (4,)
(4,)
the expand function :  [[ 0.0097797  -0.21745624  0.00357116  0.33863607]]
the expand shape :  (1, 4)
observation brut :  [ 0.00543058 -0.41262883  0.01034388  0.632443  ]
observation shape :  (4,)
(4,)
the expand function :  [[ 0.00543058 -0.41262883  0.01034388  0.632443  ]]
the expand shape :  (1, 4)
observation brut :  [-0.002822   -0.6078935   0.02299274  0.92836547]
observation shape :  (4,)
(4,)
the expand function :  [[-0.002822   -0.6078935   0.02299274  0.92836547]]
the expand shape :  (1, 4)
observation brut :  [-0.01497987 -0.80331826  0.04156005  1.2281842 ]
observation shape :  (4,)
(4,)
the expand function :  [[-0.01497987 -0.80331826  0.04156005  1.2281842 ]]
the expand shape :  (1, 4)
observation brut :  [-0.03104623 -0.9989497   0.06612373  1.5335932 ]
observation shape :  (4,)
(4,)
the expand function :  [[-0.03104623 -0.9989497   0.06612373  1.53

In [352]:
matrix = create_board(6, 7)
done = verification_plateau(matrix)
draw = False 
g = 2
print(done)

False


In [75]:
matrix = create_board(6, 7)

In [80]:
np.expand_dims(matrix, axis=2).shape

(6, 7, 1)

In [89]:
matrix.shape

(6, 7)